#!/bin/bash

cd ../backend
mvn verify
mvn "spring-boot:start" > /dev/null
cd ../http
source setup
chmod u+x boot
boot
init database
source sin user1 password
tester
cd ../backend
mvn "spring-boot:stop"
