#!/bin/bash

#
# ustawia wszystkie potrzebne, oraz wygodne, ustawienia do uruchamiania skryptów.
#
# wywołanie:
#
#		. setup
#		source setup
#

function get {
	if [[ $# == 1 ]]; then
		./get $1
	elif [[ $# == 2 ]]; then
		./get $1 $2
	elif [[ $# == 3 ]]; then
		./get $1 $2 $3
	elif [[ $# == 4 ]]; then
		./get $1 $2 $3 $4
	elif [[ $# == 5 ]]; then
		./get $1 $2 $3 $4 $5
	else
		echo "złe wywołanie"
	fi
}

function put {
	if [[ $# == 2 ]]; then
		./put $1 $2
	else
		echo "złe wywołanie"
	fi
}

function post {
	if [[ $# == 2 ]]; then
		./post $1 $2
	elif [[ $# == 3 ]]; then
		./post $1 $2 $3
	else
		echo "złe wywołanie"
	fi
}

function del {
	if [[ $# == 2 ]]; then
		./del $1 $2
	else
		echo "złe wywołanie"
	fi
}

function sin {
	if [[ $# == 2 ]]; then
		./sin $1 $2
	else
		echo "złe wywołanie"
	fi
}

function up {
	if [[ $# == 3 ]]; then
	       ./up $1 $2 $3
	else
		echo "złe wywołanie"
	fi
}	

function boot {
	./boot
}

function init {
	if [[ $# == 1 ]]; then
		./init $1
	else
		echo "zle wywolanie"
	fi
}

function tester {
	if [[ $# == 0 ]]; then
		./tester
	elif [[ $# == 1 ]]; then
		./tester $1
	else
		echo "zle wywolanie"
	fi
}


export -f get
export -f put
export -f post
export -f del
export -f sin
export -f up
export -f boot
export -f tester
export -f init


#alias get='./get'
#alias put='./put'
#alias post='./post'
#alias del='./del'
#alias up='./up'
#alias in='./in'
#alias boot='./boot'
#alias init='./init'
#alias tester='./tester'
