#!/bin/bash

#
# skrót od s(ign)in
# [ bo in nie może być nazwą funkcji >:( ]
#
# wywołanie:           . in {username} {password}  	- loguje się odpowiednimi danymi.
#
# alt. wywołanie: source in {username} {password}	-          - || -
#
# ostatni poprawnie wyłuskany token jest zapisany w pliku "token" w formacie ASCII
#
# Q: *raczej* trzeba eksportować token.


source funcs

echo "CZY TO SIE WYSWIETLI?"

if [[ $# == "2" ]]; then
	echo "{\"username\":\"$1\",\"password\":\"$2\"}" > "cache/credentials"
	lwp-request -m post -b http://localhost:8080 -c application/json authentication/signin < "cache/credentials" > "cache/response"
	cat "cache/response" | grep "error" > /dev/null
	if [[ $? == 0 ]]; then
		rm -f "cache/error"
		save_value "status" "cache/error"
		save_value "message" "cache/error"
		rm -f "cache/response"
		cat "error"
		exit 1 
	fi
	rm -f "cache/token"
	# response potrzebny do save_value
	save_value "token" "cache/token"
	rm -f "cache/response"
	token=`cat "cache/token"`
	#echo $token
	export token
else
	echo "niepoprawne wywołanie"
fi
exit 0
