# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: |
        cd backend
        #cd /var/lib/postgresql/14
        sudo sed 's/peer/password/' /etc/postgresql/14/main/pg_hba.conf > tmp
        sudo sed -i 's/scram-sha-256/password/' tmp
        sudo rm -f /etc/postgresql/14/main/pg_hba.conf
        sudo cp tmp /etc/postgresql/14/main/pg_hba.conf
        sudo cat pg_hba.conf
        sudo systemctl start postgresql
        #mvn package spring-boot:start
        #mvn clean package spring-boot:start
        cd ../http
        source setup
        chmod u+x boot
        boot
        init database
        source sin user1 password
        tester enable
        mvn spring-boot:stop
