# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: |
        cd backend
        #cd /var/lib/postgresql/14
        sudo sed 's/peer/ident/' /etc/postgresql/14/main/pg_hba.conf > tmp
        sudo sed -i 's/local.*all.*postgres.*ident//' tmp
        sudo sed -i 's/scram-sha-256/ident/' tmp
        sudo rm -f /etc/postgresql/14/main/pg_hba.conf
        sudo cp tmp /etc/postgresql/14/main/pg_hba.conf
        sudo systemctl start postgresql
        sudo -u postgres psql -c "ALTER USER postgres PASSWORD 'password';"
        sudo sed -i 's/ident/password/' /etc/postgresql/14/main/pg_hba.conf
        sudo systemctl restart postgresql
        mvn package spring-boot:start
        echo aaaaa
        cd ../http
        echo CZY_JESTESMY_PRZY_SETUPIE
        source setup
        echo CZY_JESTESMY_PRZY_CHMODZIE
        chmod u+x boot
        echo CZY_JESTESMY_PRZY_BOOTOWANIU
        boot
        echo CZY_JESTESMY_PRZY_TWORZENIU_UZYTKOWNIKOW
        init users
        echo CZY_JESTESMY_PRZY_LOGOWANIU
        source sin user1 password
        echo CZY_JESTESMY_PRZY_TWORZENIU_ZADAN
        init tasks
        echo CZY_JESTESMY_PRZY_URUCHAMIANIU_TESTOW
        tester enable
        echo CZY_JESTESMY_PRZY_ZAMYKANIU_MAVENA
        mvn spring-boot:stop
        echo CZY_JESTESMY_POZA_MAVENEM
